services:
  - type: web
    name: virtual-wallet
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: DATABASE_URL
        fromDatabase:
          name: virtual-wallet-postgres
          property: connectionString
      - key: DIRECT_URL
        fromDatabase:
          name: virtual-wallet-postgres
          property: connectionString